<!DOCTYPE html>
<html>
<head>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-6EBTM9J4LK"></script>
<script src="../g.js"></script>
    <title>cg::209022</title>
    <link rel="stylesheet" href="../c.css">
</head>
<body>
    <br><br>
    <div id = "content">
    <div id="container">
    <div id="mf">
        <a href="#" class="nonewtab" d-g="g">g</a> | 
        <a href="#" class="nonewtab" d-g="x">x</a> | 
        <a href="#" class="nonewtab" d-g="w">w</a> | 
        <a href="#" class="nonewtab" d-g="">all</a>
    </div>
    <input type="text" id="mi" placeholder="/">
    </div>

<table id="mt">
  <tr class="header">
    <th class="tbytes">Bytes</th>
    <th class="tlang">Lang</th>
    <th class="ttime">Time</th>
    <th class="tlink">Link</th>
  </tr>
<tr d-ix="0"><td>469</td><td>Brainfuck</td><td>250511T172128Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/279655#279655">JOrE</a></td></tr>
<tr d-ix="1"><td>186</td><td>Pascal</td><td>250511T171358Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/279654#279654">JOrE</a></td></tr>
<tr d-ix="2"><td>016</td><td>Vyxal</td><td>220202T150715Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/242226#242226">Jakque</a></td></tr>
<tr d-ix="3"><td>089</td><td>Python 3.8</td><td>210507T103912Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/225230#225230">Jakque</a></td></tr>
<tr d-ix="4"><td>096</td><td>Ruby</td><td>200816T135626Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209628#209628">Dingus</a></td></tr>
<tr d-ix="5"><td>156</td><td>AWK</td><td>210611T212616Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/229515#229515">Pedro Ma</a></td></tr>
<tr d-ix="6"><td>043</td><td>Japt</td><td>210507T114015Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/225233#225233">Etheryte</a></td></tr>
<tr d-ix="7"><td>nan</td><td>Pxem esolangbox notation</td><td>210505T061343Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/225108#225108">user1004</a></td></tr>
<tr d-ix="8"><td>086</td><td>Python 2</td><td>210409T064125Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/223128#223128">dingledo</a></td></tr>
<tr d-ix="9"><td>nan</td><td>Wolfram Language Mathematica</td><td>200803T213534Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209047#209047">att</a></td></tr>
<tr d-ix="10"><td>028</td><td>Klein 001</td><td>201112T194702Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/215146#215146">Wheat Wi</a></td></tr>
<tr d-ix="11"><td>140</td><td>Haskell</td><td>200805T212319Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209120#209120">Silvio M</a></td></tr>
<tr d-ix="12"><td>127</td><td>Haskell</td><td>201108T163113Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/214917#214917">Wheat Wi</a></td></tr>
<tr d-ix="13"><td>026</td><td>Keg</td><td>200804T005725Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209054#209054">lyxal</a></td></tr>
<tr d-ix="14"><td>nan</td><td>Java 10+</td><td>200816T232449Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209632#209632">user</a></td></tr>
<tr d-ix="15"><td>nan</td><td>R</td><td>200803T172156Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209032#209032">Dominic </a></td></tr>
<tr d-ix="16"><td>121</td><td>Python 3</td><td>200814T003936Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209539#209539">Quelklef</a></td></tr>
<tr d-ix="17"><td>125</td><td>R</td><td>200807T085840Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209220#209220">Dominic </a></td></tr>
<tr d-ix="18"><td>025</td><td>Quine + Cat = Hello World</td><td>200803T165429Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209029#209029">fireflam</a></td></tr>
<tr d-ix="19"><td>017</td><td>Jelly</td><td>200805T214437Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209121#209121">Jonathan</a></td></tr>
<tr d-ix="20"><td>117</td><td>PHP</td><td>200806T130130Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209174#209174">RFSnake</a></td></tr>
<tr d-ix="21"><td>032</td><td>V vim</td><td>200805T184654Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209117#209117">Beefster</a></td></tr>
<tr d-ix="22"><td>189</td><td>Python 2</td><td>200803T200634Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209042#209042">Beefster</a></td></tr>
<tr d-ix="23"><td>048</td><td>><></td><td>200804T215427Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209093#209093">SE - sto</a></td></tr>
<tr d-ix="24"><td>023</td><td>05AB1E</td><td>200804T100829Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209072#209072">Kevin Cr</a></td></tr>
<tr d-ix="25"><td>nan</td><td>Hello World + Quine = Cat</td><td>200804T203000Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209091#209091">rtpax</a></td></tr>
<tr d-ix="26"><td>051</td><td>Alice</td><td>200804T193144Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209090#209090">Oyarsa</a></td></tr>
<tr d-ix="27"><td>nan</td><td>Rust</td><td>200803T194547Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209039#209039">TehPers</a></td></tr>
<tr d-ix="28"><td>nan</td><td>Aceto</td><td>200804T121909Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209077#209077">L3viatha</a></td></tr>
<tr d-ix="29"><td>129</td><td>Python 3</td><td>200803T201447Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209043#209043">water_gh</a></td></tr>
<tr d-ix="30"><td>110</td><td>Bash</td><td>200803T215549Z</td><td><a href="https://codegolf.stackexchange.com/questions/209022/cat-quine-hello-world/209048#209048">Beefster</a></td></tr>
</table>
<div id="pu0" class="pu"><h1>Brainfuck, Hello World + Quine = Cat, 469 bytes</h1>
<p>Hello World <strong>(Requires dynamic memory)</strong></p>
<pre><code>+[--&gt;-[&gt;&gt;+&gt;-----&lt;&lt;]&lt;--&lt;---]&gt;-.&gt;&gt;&gt;+.&gt;&gt;..+++[.&gt;]&lt;&lt;&lt;&lt;.+++.------.&lt;&lt;-.&gt;&gt;&gt;&gt;+.
</code></pre>
<p>Quine:</p>
<pre><code>-&gt;++&gt;+++&gt;+&gt;+&gt;+++&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;+&gt;+&gt;++&gt;+++&gt;++&gt;&gt;+++&gt;+&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;+&gt;+&gt;&gt;+++&gt;&gt;+++&gt;&gt;&gt;&gt;&gt;+++&gt;+&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;++&gt;+++&gt;+++&gt;+&gt;&gt;+++&gt;&gt;&gt;+++&gt;+&gt;++&gt;+++&gt;&gt;&gt;+&gt;+&gt;++&gt;+++&gt;+&gt;+&gt;&gt;+++&gt;&gt;&gt;&gt;&gt;&gt;&gt;+&gt;+&gt;&gt;&gt;+&gt;+&gt;++&gt;+++&gt;+++&gt;+&gt;&gt;+++&gt;&gt;&gt;+++&gt;+&gt;++&gt;+++&gt;++&gt;&gt;+&gt;+&gt;++&gt;+++&gt;+&gt;+&gt;&gt;+++&gt;&gt;&gt;&gt;&gt;+++&gt;+&gt;&gt;&gt;&gt;&gt;++&gt;+++&gt;+++&gt;+&gt;&gt;+++&gt;&gt;&gt;+++&gt;+&gt;+++&gt;+&gt;&gt;+++&gt;&gt;+++&gt;&gt;++[[&gt;&gt;+[&gt;]++&gt;++[&lt;]&lt;-]&gt;+[&gt;]&lt;+&lt;+++[&lt;]&lt;+]&gt;+[&gt;]++++&gt;++[[&lt;++++++++++++++++&gt;-]&lt;+++++++++.&lt;]
</code></pre>
<p>Cat Program:</p>
<pre><code>+[,.]
</code></pre>
<blockquote>
<p><strong>Note: It needs a null at end of input, or the last character will repeated infinite times.</strong></p>
</blockquote>
</div>
<div id="pu1" class="pu"><h1>Pascal, Cat + Quine = Hello World, 186 Bytes</h1>
<h2>Cat Program:</h2>
<pre><code>var s:string;begin read(s);write(s)end.
</code></pre>
<h2>Quine:</h2>
<pre><code>CONST T=';BEGIN WRITE(#67#79#78#83#84#32#84#61#39,T,#39,T)END.';BEGIN WRITE(#67#79#78#83#84#32#84#61#39,T,#39,T)END.
</code></pre>
<h2>Hello World:</h2>
<pre><code>begin write(&quot;Hello World!&quot;)end.
</code></pre>
</div>
<div id="pu2" class="pu"><h1><a href="https://github.com/Vyxal/Vyxal" rel="nofollow noreferrer">Vyxal</a>, Cat + Quine = Hello, 16 bytes</h1>
<h2>Hello world, 13 bytes</h2>
<pre><code>kh\!+□⁋`I^`I^
</code></pre>
<p><a href="https://vyxal.pythonanywhere.com/#WyIiLCIiLCJraFxcISvilqHigYtgSV5gSV4iLCIiLCJhXG5iXG5jXG5kXG4iXQ==" rel="nofollow noreferrer">Try it Online!</a></p>
<h2>Cat, 7 bytes</h2>
<pre><code>kh\!+□⁋
</code></pre>
<p><a href="https://vyxal.pythonanywhere.com/#WyIiLCIiLCJraFxcISvilqHigYsiLCIiLCJhXG5iXG5jXG5kXG4iXQ==" rel="nofollow noreferrer">Try it Online!</a>qwhYOKWoeKBiyIsIiIsImFcbmJcbmNcbmRcbiJd)</p>
<h2>Quine, 6 bytes</h2>
<pre><code>`I^`I^
</code></pre>
<p><a href="https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgSV5gSV4iLCIiLCJhXG5iXG5jXG5kXG4iXQ==" rel="nofollow noreferrer">Try it Online!</a></p>
<h2>Explanation :</h2>
<pre><code>## Cat (10)

kh       # push 'Hello World' onto the stack
  \!+    # add '!' to the string
     □   # push the list of the inputs onto the stack
      ⁋  # join the element on top of the stack, with '\n' as separator
         # implicit output

## Quine (6)

`I^`     # push 'I^' on the stack
    I    # string -&gt; `string`string 
     ^   # reverse the stack
         # implicit output

## Hello (16)

kh\!+          # push `Hello World!` onto the stack
     □         #  | do
      ⁋        #  | many
       `I^`    #  | useless
           I   #  | things
             ^ # reverse the stack
               # implicit output
</code></pre>
</div>
<div id="pu3" class="pu"><h1 id="python-3.8-cat-quine-hello-101-91-89-bytes-gabx"><a href="https://docs.python.org/3.8/" rel="nofollow noreferrer">Python 3.8</a>, Cat + Quine = Hello, <s>101 91</s> 89 bytes</h1>
<h2 id="cat-32-bytes-3893">Cat (32 bytes)</h2>

<pre class="lang-python prettyprint-override"><code>a=id=&quot;&quot;
while 1:a=input(a)+&quot;\n&quot;;
</code></pre>
<p><a href="https://tio.run/##DcexDkAwEADQ3VdcOhGTWIQY/IeloWi0d5dzTePry9sev3oR9gNLKXb2@2xMlS8fHHTjf@SktW1as6KZSlnkTNGhPnCQwGYVWOgUG6uYgvrg0T2QSW5QIhj5Aw" rel="nofollow noreferrer" title="Python 3.8 (pre-release) – Try It Online">Try it online!</a></p>
<h2 id="quine-57-bytes-rc9m">Quine (57 bytes)</h2>

<pre class="lang-python prettyprint-override"><code>exec(s:='+input(id and&quot;exec(s:=%r)&quot;%s or&quot;Hello World!&quot;)')
</code></pre>
<p><a href="https://tio.run/##NcgxDsIwDADAnVeYSFUbdWRBlRjY@EHnqDElwrEjxxHw@nTixis/ewlfrkV7xy9uU11u45y4NJtShMDR/XtQ74YKou6BRAKrKMWz86Pv/a57y8hW4SkKWzAoKruGfMqNLFFirPARfYOJwFIO" rel="nofollow noreferrer" title="Python 3.8 (pre-release) – Try It Online">Try it online!</a></p>
<h2 id="hello-world-89-bytes-n1cg">Hello World (89 bytes)</h2>

<pre class="lang-python prettyprint-override"><code>a=id=&quot;&quot;
while 1:a=input(a)+&quot;\n&quot;;exec(s:='+input(id and&quot;exec(s:=%r)&quot;%s or&quot;Hello World!&quot;)')
</code></pre>
<p><a href="https://tio.run/##NcixDsIgEADQvV9xXtK0pJNxMRiGbv6Biwsp2BKBIwek@vVoYhzfS@@yUTydE7emlTMKsds35y0c5dcx1TJqMeE94sW@7DJmqYbp986Ajgb/3bPAPgMxXq33BDdibw4oBtHazGsNNpYMD2JYdIHEtLIOXai@OO@izbATP6EQgUwf" rel="nofollow noreferrer" title="Python 3.8 (pre-release) – Try It Online">Try it online!</a></p>
<h2 id="how-it-works-bssk">How it works:</h2>
<p>For the cat program:</p>
<ul>
<li><code>a=id=0</code> we assign <code>a</code> and <code>id</code> to the empty string. <code>id</code> is now evaluated as <code>False</code> (remember it for later)</li>
<li>At the first loop of <code>while 1</code>: <code>a=input(a)+&quot;\n&quot;</code> will display <code>a</code> without a new line (so the empty string) and store in <code>a</code> the first line of the input plus a newline</li>
<li>Then we loop again, displaying the input of the previous iteration until the program has written all the lines of the input and crash (<code>EOFError</code>)</li>
</ul>
<p>For the quine program:</p>
<ul>
<li>The main structure of the quine is <code>exec(s:='print(&quot;exec(s:=%r)&quot;%s)')</code>, a well known quine in python.</li>
<li>We uses <code>input()</code> instead of <code>print()</code> to avoid the trailing new line</li>
<li>the <code>+</code> at the start is here to make the program crash as soon as it finished printing to make sure the program ends.</li>
<li><code>id</code> is a python built-in. Because of that it is evaluated as <code>True</code> so <code>id and &lt;code 1&gt; or &lt;code2&gt;</code> will be equal to <code>&lt;code 1&gt;</code> (which contains the code for our quine to work).</li>
</ul>
<p>For the hello world program:</p>
<ul>
<li>remember the cat program where we assigned <code>id</code> to the empty string?</li>
<li><code>id and &lt;code 1&gt; or &lt;code2&gt;</code> will now execute <code>&lt;code2&gt;</code> since <code>id</code> is now evaluated as <code>False</code>, resulting the printing of <code>Hello World!</code></li>
<li>The <code>+</code> crashes the program avoiding looping in the cat code again</li>
</ul>
<h2 id="old-solution-cat-37-quine-64-hello-101-bytes-k54v">Old solution: cat (37) + quine (64) = hello (101 bytes)</h2>
<p>Here is my old solution using  triple quoted string and comments to &quot;squeeze&quot; the quine part and directly printing <code>&quot;Hello World!&quot;</code>. It uses some cool tricks with comments:</p>

<pre class="lang-python prettyprint-override"><code>while p:=print:id or p(input());id=""&#9;&#9;&#9;&#9;&#9;&#9;&#9;&#9;&#9;# cat (37 bytes)
                                     "";exec(s:='input(\'"";exec(s:=%r)\'%s)#"""-p("Hello World!")#')&#9;# quine (64 bytes)
while p:=print:id or p(input());id="""";exec(s:='input(\'"";exec(s:=%r)\'%s)#"""-p("Hello World!")#')&#9;# hello (101 bytes)
</code></pre>
<p><a href="https://tio.run/##TYwxDsIwDEV3TmFaVUkGJhYU1IGNG7B0qdrQWqSx5bgqnD5UYuGP7z19/uhM6XxhKWWbMQZg37JgUo8jkABbTLyqde6KY1vtu4Z3GGz2rfmZzvyxRlxnmuzqPTyxre4hRoIHSRyPlauNK@Um07qEpBme@//QK7DQJP1yWNaoGDGFDBvJC5QIPH8B" rel="nofollow noreferrer" title="Python 3.8 (pre-release) – Try It Online">Try it online!</a></p>
<p>Who said that comments were not usefull in codegolfing?</p>
</div>
<div id="pu4" class="pu"><h1 id="ruby-cat-quine-hello-world-100-97-96-bytes-l17p"><a href="https://www.ruby-lang.org/" rel="nofollow noreferrer">Ruby</a>, Cat + Quine = <em>Hello World!</em>, <sup><s>100</s> <s>97</s></sup> 96 bytes</h1>
<p>Reading the source code is prohibited for quines but there is no such rule for <em>Hello World!</em> programs. We exploit this fact using Ruby's <code>DATA</code>/<code>__END__</code> mechanism. If <code>__END__</code> appears alone on any line in the code, execution terminates there. However, any further code is accessible via the constant <code>DATA</code>, which is initialised to a <code>File</code> object containing all of this non-executable 'data'.</p>
<h3 id="cat-qa4f">Cat</h3>

<pre class="lang-ruby prettyprint-override"><code>$&gt;&lt;&lt;(DATA||=$&lt;).read;a
</code></pre>
<p><a href="https://tio.run/##KypNqvz/X8XOxkbDxTHEsabGVsVGU68oNTHFOvH//5CMVIXkxBKFYiDOz1MoAXJzE0sA" rel="nofollow noreferrer" title="Ruby – Try It Online">Try it online!</a></p>
<p>The idiomatic <code>||=</code> operator sets the value of the variable <code>DATA</code> only if it is not already defined. In this case, <code>DATA</code> is not defined because the program does not contain <code>__END__</code>. In effect, the first part of the code therefore reduces to <code>$&gt;&lt;&lt;$&lt;.read</code>, where <code>$&lt;</code> and <code>$&gt;</code> point to STDIN and STDOUT, respectively. For later use, the final <code>a</code> (which is an undefined variable) throws an error, which is inconsequential here.</p>
<h3 id="quine-icvc">Quine</h3>

<pre class="lang-ruby prettyprint-override"><code>eval$s=%q($&gt;&lt;&lt;&quot;eval$s=%q(#$s)
__END__
Hello World!&quot;)
__END__
Hello World!
</code></pre>
<p><a href="https://tio.run/##KypNqvz/P7UsMUel2Fa1UEPFzsZGCcFVVinW5IqPd/VziY/n8kjNyclXCM8vyklRVMIu/P9/SEaqQnJiiUIxEOfnKZQAubmJJQA" rel="nofollow noreferrer" title="Ruby – Try It Online">Try it online!</a> or <a href="https://tio.run/##S0oszvj/vzxZQTdZQS8zr6C0RK8kM9@aKzfFtLg0F0WoqDSpEklAoUYBoghDxvr//9SyxByVYlvVQg0VOxsbJQRXWaVYkys@3tXPJT6eyyM1JydfITy/KCdFUQm7MAA" rel="nofollow noreferrer" title="Bash – Try It Online">verify quine</a>.</p>
<p>All of the real work is done in the first line, which is a basic Ruby quine template. With <code>__END__</code> now making an appearance, it shouldn't be too hard to see where this is going.</p>
<h3 id="hello-world-40bl"><em>Hello World!</em></h3>

<pre class="lang-ruby prettyprint-override"><code>$&gt;&lt;&lt;(DATA||=$&lt;).read;a
eval$s=%q($&gt;&lt;&lt;&quot;eval$s=%q(#$s)
__END__
Hello World!&quot;)
__END__
Hello World!
</code></pre>
<p><a href="https://tio.run/##KypNqvz/X8XOxkbDxTHEsabGVsVGU68oNTHFOpErtSwxR6XYVrVQA6RACcFVVinW5IqPd/VziY/n8kjNyclXCM8vyklRVMIu/P9/SEaqQnJiiUIxEOfnKZQAubmJJQA" rel="nofollow noreferrer" title="Ruby – Try It Online">Try it online!</a></p>
<p>Finally we have <code>DATA</code> and <code>__END__</code> together. Unlike in the <em>cat</em> program, <code>DATA</code> is defined this time: it's a <code>File</code> object containing <code>Hello World!</code>. Once this has been printed, there is no further output because of the error thrown by the final <code>a</code> (undefined) in the first line.</p>
</div>
<div id="pu5" class="pu"><h1><a href="https://www.gnu.org/software/gawk/manual/gawk.html" rel="nofollow noreferrer">AWK</a>, Cat + HW = Quine, 156 bytes</h1>
<pre><code>BEGIN{k=1}1;BEGIN{if(k){printf a=&quot;BEGIN{k=1}1;BEGIN{if(k){printf a=%c%s%c,34,a,34,34,34;exit}print%cHello World!%c}&quot;,34,a,34,34,34;exit}print&quot;Hello World!&quot;}
</code></pre>
<p><a href="https://tio.run/##SyzP/v/fydXd068629aw1tAaws5M08jWrC4oyswrSVNItFUiqEI1WbVYNVnH2EQnEUSAkXVqRWZJLViJarJHak5OvkJ4flFOiqJqcq0STqVKyCqVav//d04sAQA" rel="nofollow noreferrer" title="AWK – Try It Online">Try it online!</a></p>
<p>This is the overall algorithm:</p>
<pre><code>BEGIN{k=1}1;
BEGIN{if(k){
    print&quot;Quine&quot;;exit
    }
print&quot;Hello, World!&quot;
}
</code></pre>
<h2>Cat</h2>
<pre><code>BEGIN{k=1}1;
</code></pre>
<h2>Hello World</h2>
<pre><code>BEGIN{if(k){printf a=&quot;BEGIN{k=1}1;BEGIN{if(k){printf a=%c%s%c,34,a,34,34,34;exit}print%cHello World!%c}&quot;,34,a,34,34,34;exit}print&quot;Hello World!&quot;}
</code></pre>
</div>
<div id="pu6" class="pu"><h1><a href="https://github.com/ETHproductions/japt" rel="nofollow noreferrer">Japt</a>, Quine + Cat = Hello World, 43 bytes</h1>
<p>All of the complexity is jammed into making a quine that includes a variable that holds <code>Hello World!</code>. Cat simply outputs the default input and the Hello World merger reuses the variable from the quine.</p>
<h2><a href="https://ethproductions.github.io/japt/?v=1.4.6&amp;code=IkhlbGxvIFdvcmxkISIKImlRILJpUmlRaVVpUSJpUSCyaVJpUWlVaVE=&amp;input=" rel="nofollow noreferrer">Quine, 41 bytes</a></h2>
<pre><code>&quot;Hello World!&quot;             // U = &quot;Hello World!&quot;
&quot;iQ ²iRiQiUiQ&quot;iQ ²iRiQiUiQ // A bunch of messy string manipulations to make this a quine
</code></pre>
<h2><a href="https://ethproductions.github.io/japt/?v=1.4.6&amp;code=ClU=&amp;input=ImZvb2JhciI=" rel="nofollow noreferrer">Cat, 2 bytes</a></h2>
<pre><code>
U // Output the default first input
</code></pre>
<h2><a href="https://ethproductions.github.io/japt/?v=1.4.6&amp;code=IkhlbGxvIFdvcmxkISIKImlRILJpUmlRaVVpUSJpUSCyaVJpUWlVaVEKVQ==&amp;input=" rel="nofollow noreferrer">Hello World, 43 bytes</a></h2>
<pre><code>&quot;Hello World!&quot;             // U = &quot;Hello World!&quot;
&quot;iQ ²iRiQiUiQ&quot;iQ ²iRiQiUiQ // Throwaway line
U                          // Output U
</code></pre>
</div>
<div id="pu7" class="pu"><h1><a href="https://esolangs.org/wiki/Pxem" rel="nofollow noreferrer">Pxem</a> (<a href="https://github.com/hakatashi/esolang-box#pxem" rel="nofollow noreferrer">esolang-box notation</a>), Hello World: 48 bytes + Quine: 110 bytes = Cat: 158 bytes.</h1>
<p>Unprintables are escaped.</p>
<h2>Hello World</h2>
<pre><code>.f!.zHello World.p.d.a.w.c.z.w.o.i.c\001.+.a.d.a.a

</code></pre>
<h2>Quine</h2>
<pre><code>!Be!?BzBc!!B+BzXXFBaBcFBzBsXXFBBaBsBtBvBmBvBcAcB-BaBsBp&quot;.e!?.z.c!!.+.zXXF.a.cF.z.sXXF..a.s.t.v.m.v.cAc.-.a.s.p
</code></pre>
<h2>Cat</h2>
<pre><code>.f!.zHello World.p.d.a.w.c.z.w.o.i.c\001.+.a.d.a.a
!Be!?BzBc!!B+BzXXFBaBcFBzBsXXFBBaBsBtBvBmBvBcAcB-BaBsBp&quot;.e!?.z.c!!.+.zXXF.a.cF.z.sXXF..a.s.t.v.m.v.cAc.-.a.s.p
</code></pre>
<h2><a href="https://tio.run/##jVhtV9rKFv7urxjSSCaGvAyiUmJUQGs5R6laj9cK6IpJEDAkNAmKBs5f790zCQKht@u6lmbm2c9@mb1nTyY@h71fnz5ZpmntWs7jXrf4uUhMs@tsm1Z52@qWSFEj1k5Z23N2i93iRuhESHbG@nhohs9I04pF3ZmM/CBCZ/WH6tmZUddx9DZy0JMTWb7XzefZzPKHQ9OzxQPVdl5Ub@y6qHiQJ/l8qnxRvf5qcDxOeUgezQ0wkcjH9CFVZslAnnFzt/80G7cP36@PjaKmbc/Bi2/fG7dnPx7q366uTurXBtFbiOPjWvX714ebk6vvjW/NivQ245CB3lAnn2er8tHID/uTZCbVEpW7/6HhDMeuGTko7DG@P4pg@OoHdjhy@1E@b7p9M0TyExL4mEgcf8TNBEOgTyGfb/5zdlY/PzYqzAem/mw97PW7kc7GiPJSwLF6PuI/idQzoZ5z4Kjou/ZBHlL/YrqIy6Gu6YYON50uy5hppj2Zho6NhFCdqG@qHsKfd1VgBt9RhyoxFnDmqhYWsQ9FqHpIfonGZBoFSK6HqN3S5M8dJLTa3lZHmD4FzggpiXH1vrTLq3GlqvOPelNX2x6bX4C7e0Vpe6qqP1b1WTJt3VM7hBR5daTq0TJY1tYxQgiv@hlw7/M6Rghoe1lieR0j2g6v9rPE7XXsM/Aeshh4tjLY7t46Rggoh9n1ba9jhECIL1ni7jpGNMhYNxu2to4RDTLmZGP8vI4RUuLVIOu6uI4RAtqvWeLeOgbnBQ8bLUMsr2OkCDG@ZYmf1zFShHjes0XQfoNBOGZ20TvrGCGQ2yjrubSOEQ3CGWbzvbeOEQ3CsbOuy@tYCcovZTEIUc5g28DLZTGIms9iEMwmxWbCFFtmelzYYtqUrF/V@JQ25US3of9OqXYbK22xjdse/atstUVebW@3i22iAitUlS3o1slqf1dcnc/Faut18vZu2h01Fzf1RxcMzvQ3aHYVqbrauk@ldIvzKrLVFRuyh4TUfev@qNABvxABbiVDCKF4hGgIvZST4EjZAhGLLPEO6xmxMHm1QNFHCAFKHMMsF4cwqqoj/fES0IRWOAIDH0T7g2irx3PiCm0uSfNQCXQ@TtwdIWoajjjGRtU5ElVZavlcEyRtr4Xk986WTa1FwRICS2L56SSLVZnIBNqI1TRZnJlozSDayuWHSYXFFl1mztw0H18hM8dVyMskLS7L7CJvSX5OU0vsNwkliSSt@u8UBTR/dSwVRO13sWs@Oq5hcG3CiTFbCW6NfK//YIUvXSeIhlKO35Q7lN0mWNTVp4RD92M7JoX2jIoucJukMnM5pHD8iDlaEK5AtQ9hzFW4I67A3Iqz1OEq/0/kY159DBzzmU2gblXMub4/Qp4foaEZWb2@98QBVZgvV8Ki@oiJSPkyG8vJJMcmGhvzMP6ZjjfZGDjQh6wHha4fpGmCYHRdjAX9o0GFmSCKv3qO6/qGoHRzyvtXOkb/8QPXVkaKrZjKq2Ip7/DXV/qK1dY0okiAUonZ9oSNn@O@5xhCrubkDmvvNSuXq0m199vbLzWzZn0BJKRjmIS1qPZSG8KvVbVqMkNGnAJqYB7UwCxVA7vWF0ComgKTUImUF2UIv6CmyAwZCRsbQ992jF7y@Jk8rI0NywwdxNMZ6nuo1bM64gb60qyen8Ctjq2T29D1n0sgi5@CTmiCgfq35vVJ89rIWLJENJfMVeYaeBT0vagLtxxmkk953PTVQrIlwj3mVxhYhlA7OW00Y9izUug4thgGcL/EbDjrjj0r6vseusDHYvy99Vz4G4sd41iHYUeSFvITLMaBE40DD@Uk4Cwkfy0kgB@QheTvhYSaWwiuVwTUpUyWxLf4SoyvDGCxMGRZT8lXC84Y18WYrR/VF@gpvircfdiG@7ML@TrQDnmtIi8F9jVxwBOd9c09a0oJ2ofjxBUIJdC6@3@o@7FnLPmu4vN5ROdTDjY65J/e0fsRWnI9gqW/9vqug3OQUtFfziRMYgCn0zG@BdlC4OFG4aZwXHBFWkWmGN8YwNFdw3W8p6iHb0SdtlsDLvqNfcPVxTHGxwasJYwCfFNoSFKBiOK/HFsXd3gslcqV0o44Wzjpg/cLfLri@AGfF@qFu8IPMT43OOWhgppwXpjIdqz@EC7esFjnyQngORpHnF43QF2/gxhoLLTjIdzS3n49n6/v75RFdgLpgNX/5e5Lre2dDg@H551RKsn1VDk5pICCy4kaKUFC6oaxXRTjhALfRFHfGzszmnFKre@XysA52NkTKZQ4X7hNLIs/DPwDekkulXVaPf0C3239WFqrNc/@Bb5eSUI4F9wuF@sFajIo3Ihxw9CYx4HB9jGkf0C3bWEgyx3jhhaKzhodBkIdOmw@6CylPli4hoxi1p/iFt0DSw5fF02zHs0EXxaYrxy0I81wDmaXbIvcGJf7lJvq3iyU3v6odPB7pfePMKgWC0NeCSWaL6YHvWusiIYgeqaHGnwyXmAqXxI@YhMSmmzxv@gOv8DmIahLJs1E5TbNiL44MbYMIhe3sLmviVu0ZvBcSurPrL1B2jG36WLxYMsVYceAG07ZhDemAruRq6A7J4ALZP@lH4IZjm4UWhTzcHDgHg423Yq7OaiwscrGUKNZcsJCZIbWge0AX7mZs5mbWiInLILrQiZWWB9n9/pX5x8@Oo3kbZ1ckeAGCm9v@vEvB94zmVpjGNkCEpDcLc5f63Cju8B5kX79LoXjsM2cXBdi2LhsQz9Lki5Jg31MD2G6aSHlSfoH6RQGov77ZdDl2o7rRA6COkMrpMcTNIgkNfZBXSJJS7A3TYNZlAj0SXLoS8m8MxN0@qai/xmBO6SF2H9PxrRD/CH9XwCAwRq4yKFdQnKztEKYTvEoBLmPRn274ET9oVMYWaNx4SV8120zcsTlGpT@/OWPIrPvwr2@tJRg@m0Rl@n9jt0ihan5@gy2kGnIRVLaK5W3d0tlJMSmZPDa7KR5nL41TLgScRv/d/1Tq2l26IODAsALn2Migdfgcgo/HAqT8mBu0@cKvCYK04kZPEEOGhOUVm6CNn79Fw" rel="nofollow noreferrer" title="ksh – Try It Online">Try it online!</a></h2>
<p>Use variable <code>mode</code> to switch programs.</p>
<h2>How it works</h2>
<p>The Hello World program consists of several parts, as in:</p>
<pre><code># branch if content begins with '!' or not
.f!.z
  # Hello World program
  # Note that '!' is recycled here
  Hello World.p.d
.a
.w.c.z
  # Cat program
  # Note that content of stack is cleared before entrying here
  .w.o.i.c\001.+.a.d
.a.a\n
</code></pre>
<p>Quine is <a href="https://codegolf.stackexchange.com/a/221399/100411">recycled from here</a>.</p>
<p>Cat program uses this specification:</p>
<blockquote>
<p>The first line is the file name of the pxem code.</p>
<p>The rest is the content of the pxem code.</p>
</blockquote>
</div>
<div id="pu8" class="pu"><h1><a href="https://docs.python.org/2/" rel="nofollow noreferrer">Python 2</a>, Quine + Cat = Hello World, 86 bytes</h1>
<h3><a href="https://tio.run/##K6gsycjPM/r/PzPFVh2IVYusC4oy80oUMlNUVTNT1BG8zJT//wtLM/NSAQ" rel="nofollow noreferrer" title="Python 2 – Try It Online">Quine</a> (35 bytes)</h3>

<pre class="lang-python prettyprint-override"><code>id='id=%r;print id%%id';print id%id
</code></pre>
<h3><a href="https://tio.run/##K6gsycjPM/r/X9tAS109MS9F3SM1JydfITy/KCdFUZ2rPCMzJ1Vd3S4zxaqgKDOvRKEosTw@M6@gtERD8///5MQSLiAqAQA" rel="nofollow noreferrer" title="Python 2 – Try It Online">Cat</a> (51 bytes)</h3>

<pre class="lang-python prettyprint-override"><code>+0*''and'Hello World!'
while''&gt;id:print raw_input()
</code></pre>
<h3><a href="https://tio.run/##K6gsycjPM/r/PzPFVh2IVYusC4oy80oUMlNUVTNT1BG8zBRtAy119cS8FHWP1JycfIXw/KKcFEV1rvKMzJxUdXW7zBQriOKixPL4zLyC0hINzf//AQ" rel="nofollow noreferrer" title="Python 2 – Try It Online">Hello World</a> (86 bytes)</h3>

<pre class="lang-python prettyprint-override"><code>id='id=%r;print id%%id';print id%id+0*''and'Hello World!'
while''&gt;id:print raw_input()
</code></pre>
</div>
<div id="pu9" class="pu"><h1><a href="https://www.wolfram.com/wolframscript/" rel="nofollow noreferrer">Wolfram Language (Mathematica)</a>, Quine + Cat = Hello World, <s>15+28=43</s> 15 + 22 = 37 bytes</h1>
<p>3 functions.</p>
<h3>Quine</h3>
<pre><code>ToString[#0] &amp; 
</code></pre>
<p><a href="https://tio.run/##y00syUjNTSzJTE78n2b7PyQ/uKQoMy89WtkgVkFN4X8AkFPikOagVFiamZeq9B8A" rel="nofollow noreferrer" title="Wolfram Language (Mathematica) – Try It Online">Try it online!</a></p>
<h3>Cat</h3>
<pre><code>#/.#_:&gt;&quot;Hello World!&quot;&amp;
</code></pre>
<p><a href="https://tio.run/##y00syUjNTSzJTE78n2b7X1lfTzneyk7JIzUnJ18hPL8oJ0VRSe1/QFFmXolDmoNScmKJ0n8A" rel="nofollow noreferrer" title="Wolfram Language (Mathematica) – Try It Online">Try it online!</a></p>
<h3>Hello World</h3>
<pre><code>ToString[#0] &amp; #/.#_:&gt;&quot;Hello World!&quot;&amp;
</code></pre>
<p><a href="https://tio.run/##y00syUjNTSzJTE78n2b7PyQ/uKQoMy89WtkgVkFNQVlfTzneyk7JIzUnJ18hPL8oJ0VRSe1/AFBJiUOag1IGWLwcJK70HwA" rel="nofollow noreferrer" title="Wolfram Language (Mathematica) – Try It Online">Try it online!</a></p>
<hr />
<h3><s>HW+Q=C,46+58=104 Q+C=HW,43+48=91</s> Cat + Quine = Hello World, 49 + 37 = 86 bytes</h3>
<p><b>Cat</b></p>
<pre><code>Print[#/._@_-&gt;&quot;Hello World!&quot;]&amp;@$ScriptInputString
</code></pre>
<p><a href="https://tio.run/##y00syUjNTSzJTE78/z@gKDOvJFpZXy/eIV7XTskjNScnXyE8vygnRVEpVs1BJTi5KLOgxDOvoLQkuASoNv3//@TEEgA" rel="nofollow noreferrer" title="Wolfram Language (Mathematica) – Try It Online">Try it online!</a></p>
<p><b>Quine</b></p>
<pre><code>Print[ToString[#0, InputForm][]] &amp; []
</code></pre>
<p><a href="https://tio.run/##y00syUjNTSzJTE78/z@gKDOvJDokP7gEyEiPVjbQUfDMKygtccsvyo2Njo1VUFOIjv3/v7A0My8VAA" rel="nofollow noreferrer" title="Wolfram Language (Mathematica) – Try It Online">Try it online!</a></p>
<p><b>Hello World</b></p>
<pre><code>Print[#/._@_-&gt;&quot;Hello World!&quot;]&amp;@$ScriptInputStringPrint[ToString[#0, InputForm][]] &amp; []
</code></pre>
<p><a href="https://tio.run/##y00syUjNTSzJTE78/z@gKDOvJFpZXy/eIV7XTskjNScnXyE8vygnRVEpVs1BJTi5KLOgxDOvoLQkuASoNh2iISQfwotWNtBRAMu65RflxkbHxiqoKUTH/v@fATaoHGQQAA" rel="nofollow noreferrer" title="Wolfram Language (Mathematica) – Try It Online">Try it online!</a></p>
</div>
<div id="pu10" class="pu"><h1><a href="https://github.com/Wheatwizard/Klein" rel="nofollow noreferrer">Klein</a> 001, Quine + Cat = Hello World, 28 bytes</h1>
<h2>Quine, 11 bytes</h2>
<p><em>This is Martin Ender's quine from <a href="https://codegolf.stackexchange.com/a/121511/56656">here</a></em></p>
<pre><code>:?\:2+@&gt; &quot;

</code></pre>
<p><a href="https://tio.run/##y85Jzcz7/9/KPsbKSNvBTkGJ6////wYGhv91HQE" rel="nofollow noreferrer" title="Klein – Try It Online">Try it online!</a></p>
<h2>Cat, 17 bytes</h2>
<pre><code>@ &gt;&quot;Hello world!&quot;
</code></pre>
<p><a href="https://tio.run/##y85Jzcz7/99BwU7JIzUnJ1@hPL8oJ0VR6f///7rJ/w0MDP8n5uTkFAMA" rel="nofollow noreferrer" title="Klein – Try It Online">Try it online!</a></p>
<h2>Hello World, 28 bytes</h2>
<pre><code>:?\:2+@&gt; &quot;
@ &gt;&quot;Hello world!&quot;
</code></pre>
<p><a href="https://tio.run/##y85Jzcz7/9/KPsbKSNvBTkGJy0HBTskjNScnX6E8vygnRVHp////BgaG/3UdAQ" rel="nofollow noreferrer" title="Klein – Try It Online">Try it online!</a></p>
</div>
<div id="pu11" class="pu"><h1>Haskell, Cat + Quine = Hello World, 140 bytes</h1>
<h2>Cat</h2>
<pre><code>b=interact id
main=b where c=1;
</code></pre>
<h2>Quine</h2>
<pre><code>main=putStr a&gt;&gt;print a;b=putStrLn &quot;Hello world!&quot;;a=&quot;main=putStrLn a&gt;&gt;print a;b=putStrLn \&quot;Hello world!\&quot;;a=&quot;
</code></pre>
<h2>Hello World!</h2>
<pre><code>b=interact id
main=b where c=1;main=putStr a&gt;&gt;print a;b=putStrLn &quot;Hello world!&quot;;a=&quot;main=putStrLn a&gt;&gt;print a;b=putStrLn \&quot;Hello world!\&quot;;a=&quot;
</code></pre>
<p>We exploit the rules of variable shadowing. The cat program simply calls the global <code>b</code>, defined as <code>interact id</code> (a standard cat in Haskell). We declare a variable <code>c</code> that's never used, simply so we can concatenate later. The quine is pretty standard; we define a variable <code>b</code> that we never use, but otherwise it simply prints its payload and exits.</p>
<p>Here's a version of &quot;Hello world&quot; with better spacing.</p>
<pre><code>b = interact id
main = b
  where c=1
        main=putStr a&gt;&gt;print a
        b=putStrLn &quot;Hello world!&quot;
        a=&quot;main=putStrLn a&gt;&gt;print a;b=putStrLn \&quot;Hello world!\&quot;;a=&quot;
</code></pre>
<p><code>main</code> simply calls <code>b</code>, but this time is calls the locally-declared <code>b</code>, which prints &quot;Hello world!&quot;. All of the other variables are unused.</p>
</div>
<div id="pu12" class="pu"><h1><a href="https://www.haskell.org/" rel="nofollow noreferrer">Haskell</a>, Cat + Quine = Hello World, 127 bytes</h1>
<h2>Cat, 27 bytes</h2>
<pre class="lang-haskell prettyprint-override"><code>o=interact id
main=o where 
</code></pre>
<p><a href="https://tio.run/##DcnRDcAgCAXA/07BAo7gMERJfBGhVZuOT/29a7y6qEZKhTc9L0yoHXD6fGoNz7Atk8sm1GswLJ9qMoUiuOuq43LADeb3Dw" rel="nofollow noreferrer" title="Haskell – Try It Online">Try it online!</a></p>
<h2>Quine, 100 bytes</h2>
<pre class="lang-haskell prettyprint-override"><code>o=putStr&quot;Hello, world!&quot;;main=putStr$(++)&lt;*&gt;show$&quot;o=putStr\&quot;Hello, world!\&quot;;main=putStr$(++)&lt;*&gt;show$&quot;
</code></pre>
<p><a href="https://tio.run/##y0gszk7Nyfmvq5ucWKJQWJqZl6qQARTIVyjPL8pJ@Z9vW1BaElxSpOQBEtSBiCoqWecmZuZBpVQ0tLU1bbTsijPyy1WUYBpiUHXE4NHy/39idk5xSi5XfmZmfl5mXn4BAA" rel="nofollow noreferrer" title="Haskell – Try It Online">Try it online!</a></p>
<h2>Hello World</h2>
<pre class="lang-haskell prettyprint-override"><code>o=interact id
main=o where o=putStr&quot;Hello, world!&quot;;main=putStr$(++)&lt;*&gt;show$&quot;o=putStr\&quot;Hello, world!\&quot;;main=putStr$(++)&lt;*&gt;show$&quot;
</code></pre>
<p><a href="https://tio.run/##fcsxEoIwEIXhnlOsGQoVOYHGmt6WZofsTHYIWUyW4fgRZSxsbN//Po95pBBK2w6o8Fw4EvhtEFglBVfEclRKOCiwqybkaLfkKRGInRd9aDLd@3/ZwcFcP6c91cemOd3O9@xlrc0X9L@i/0NKwTFkN1XCLJGjzC8" rel="nofollow noreferrer" title="Haskell – Try It Online">Try it online!</a></p>
<h2>Explanation</h2>
<p>The main trick in this  answer is scoping.  In the cat we have a simple program.  We have a <code>main</code> which is just defined to be <code>o</code>, which is a cat program.  At the end of the program there is a <code>where</code> which opens a new scope.  This will make our entire quine program attached to the scope of the main program.  Two things are solved by doing this.</p>
<ul>
<li><p>Since the quine program's <code>main</code> is not defined in the global scope we avoid the duplicate main declaration error.</p>
</li>
<li><p>We can declare a version of <code>o</code> that overrides the one in the global scope.  Our quine program declares <code>o</code> to be a hello world program.</p>
</li>
</ul>
<p>The overall technique is very similar to <a href="https://codegolf.stackexchange.com/a/209120/56656">Silvio Mayolo's answer</a>, however improves upon it in two ways.</p>
<ul>
<li><p>Silvio Mayolo's answer declares a variable <code>c=1</code>, which is never used (I am not sure why this is done.  Removing it doesn't break anything).  This does not have this.</p>
</li>
<li><p>I used a shorter quine technique.  I took a glance at Silvio Mayolo's quine and I don't know how it works, but it is longer than mine.</p>
</li>
</ul>
</div>
<div id="pu13" class="pu"><h1><a href="https://github.com/JonoCode9374/Keg" rel="nofollow noreferrer">Keg</a>, Hello World + Quine = Cat, 26 bytes</h1>
<pre><code>«H%c¡|,!«``:[④|᠀,]`:[④|᠀,]
</code></pre>
<p><a href="https://tio.run/##y05N////0GoP1eRDC2t0FA@tTkiwin40cXHNwwUNOrHI7P//iwE" rel="nofollow noreferrer" title="Keg – Try It Online">Try it online!</a></p>
<h2>How it Works</h2>
<h3>Hello World</h3>
<pre><code>«H%c¡|,!«`
</code></pre>
<p><a href="https://tio.run/##y05N////0GoP1eRDC2t0FA@tTvj/HwA" rel="nofollow noreferrer" title="Keg – Try It Online">Try it online!</a></p>
<p>This is my answer to the HW challenge with some additional string closing syntax. Why? Because a) the main string needs closing to be concatenated and b) the end ``` is needed to &quot;ignore&quot; the quine part</p>
<h3>Quine (non-trivial)</h3>
<pre><code>`:[④|᠀,]`:[④|᠀,]
</code></pre>
<p><a href="https://tio.run/##y05N//8/wSr60cTFNQ8XNOjEIrP//wcA" rel="nofollow noreferrer" title="Keg – Try It Online">Try it online!</a></p>
<pre><code>`:[④|᠀,]`           
</code></pre>
<p>Push the string <code>:[④|᠀,]</code> to the stack</p>
<pre><code>:[④|᠀,]
</code></pre>
<p>Duplicate the string and start an if-block. The if block uses the truthiness of the t.o.s to determine which branch is to be executed. In this case, the string is truthy, so the <code>④</code> is executed (printing the string raw). Implicit output then prints the string nicely.</p>
<h3>Concatenation</h3>
<pre><code>«H%c¡|,!«``
</code></pre>
<p>Push the string <code>Hello, World!</code> followed by an empty string onto the stack.</p>
<pre><code>:[④|᠀,]
</code></pre>
<p>Duplicate the top of the stack (an empty string) and start the if block. Empty strings are considered falsey, so the <code>᠀,</code> branch is executed. This takes input and prints it.</p>
<pre><code>`:[④|᠀,]
</code></pre>
<p>Push the string <code>:[④|᠀,]</code> and don't do anything with it.</p>
</div>
<div id="pu14" class="pu"><h1>Java 10+, Cat + Quine = Hello World, 384 (135 + 249) bytes</h1>
<h2><a href="https://tio.run/##LcyxDoIwEIDh2bdonGCwEHFAHUw0Jg5OonEwDhd6mEK5ajlAQnh2ZHD9k@/PoYFFropx1MToMkhRHPqKgXUqGquVKEGTl7DT9Ho8we@TrmIspa1ZvqfIhry9tQaB5PVyO@4IW5FPV1mzNjJJgQid91eafEn45bMm9PzN/ITGWHG3zqi5vx2GIBhHyKtCZXE4W3aRcFG8Dj9du/oB" rel="nofollow noreferrer">Cat</a>, 135 bytes</h2>
<pre class="lang-java prettyprint-override"><code>interface C{static void main(String[]a){System.out.println(Boolean.TRUE?new java.util.Scanner(System.in).nextLine():&quot;Hello World&quot;);}}//
</code></pre>
<h2><a href="https://tio.run/##y0osS9TNSsn@/z8zryS1KC0xOVXBNzEzr7q4JLEkM1mhLD8zRSEXKKARXFKUmZceHZuoWV2WWKRQbKuE0BFIhHLVZNVi1WTr4MriktRcvfzSEr0CoIqSNI1iHWMTHTBhaKBpXVurmoww2Ck/Pyc1Ma86CUIrhASFutqmJeYUp1rXKhFhFhdxRv3/DwA" rel="nofollow noreferrer">Quine</a>, 249 bytes</h2>
<p>(note: TIO doesn't let me run the code unless I rename my interface from <code>Q</code> to <code>Main</code>, but just know that it's supposed to be named the former)</p>
<pre class="lang-java prettyprint-override"><code>interface Q{static void main(String[]a){var s=&quot;interface Q{static void main(String[]a){var s=%c%s%c;System.out.printf(s,34,s,34,10);}}%cinterface Boolean{boolean TRUE=false;}&quot;;System.out.printf(s,34,s,34,10);}}
interface Boolean{boolean TRUE=false;}
</code></pre>
<h2><a href="https://tio.run/##lY/BasJAEIbvfYolENiAXSt6apBCodBDe9AoHqSHcTMpm66zZXeMSsizx2gFwYPYywz8zHx8fwkVPJb5T9saYvQFaBSfYKgODGy0qJzJxboLZMbe0PfyC5I62wfGtXIbVr9dyJbkq3MWgdRsOn97IdyKsgOrDRurMg1E6OX5y1CiCHf8YQhl8hy9o7VOLJy3eZSkTdPvX0wmNzUq8CKMo/@dxzoOsU6vKxQy9Iaj3mkMno4esb6Az@3q1d8Wx5bjAmzAtInuYD3ch2rbAw" rel="nofollow noreferrer">Hello World</a>, 384 bytes</h2>
<pre class="lang-java prettyprint-override"><code>interface C{static void main(String[]a){System.out.println(Boolean.TRUE?new java.util.Scanner(System.in).nextLine():&quot;Hello World&quot;);}}//interface Q{static void main(String[]a){var s=&quot;interface Q{static void main(String[]a){var s=%c%s%c;System.out.printf(s,34,s,34,10);}}%cinterface Boolean{boolean TRUE=false;}&quot;;System.out.printf(s,34,s,34,10);}}
interface Boolean{boolean TRUE=false;}
</code></pre>
<p>Again, the TIO link contains an interface called <code>Main</code>, but it's actually <code>C</code>, the cat program.</p>
<p>It redefines <code>Boolean.TRUE</code> to be <code>false</code> when the quine is concatenated to the cat.</p>
</div>
<div id="pu15" class="pu"><h1><a href="https://www.r-project.org/" rel="nofollow noreferrer">R</a>, Quine + hello, world = cat; <s>48 + 49</s> ... 43 + 44 = 87 bytes</h1>
<p>Or <strong><a href="https://tio.run/##lY9BC4IwGIbv@xVrFzeY0V0UQogOXqQdAzVbMRhbuFlK2F9fUy8JQXT8no/3eb@vcULdhREnyfGhN2vDrdR15ae6svyqmx7GEGVpsc0yROG8G1GKCAEgrWx8aVVthVa4I08XhAmLfBSbvNWWY0YoIwH8Rl@7MOmjUlxKzJINRXsupYYP3cjzCtGOuAHkrVB8UQD@KAADmJzF5FxqfpX77PgcRkLdWovIfAomYCxBR@XJh9tz9wY" rel="nofollow noreferrer">75 bytes</a></strong> as internal code of functions and not including <code>function(){}</code> wrappers.</p>
<p><em>Edit: -14 bytes thanks to Robin Ryder!</em></p>
<p>Nontrivial quine:</p>

<pre class="lang-r prettyprint-override"><code>'-&gt;T;cat(sQuote(T),T)' -&gt;T;cat(sQuote(T),T)
</code></pre>
<p><a href="https://tio.run/##K/qfmVeWWZyZlJOqEVxZrFecWpKTn5wI5CUnlqSm5xdVKtgqKPk4xzv6@CjpKEDkQELOSpqa/9V17UKsgQo1igNL80tSNUI0dUI01RWwif7n@g8A" rel="nofollow noreferrer" title="R – Try It Online">Try it online!</a></p>
<p>Hello,world:</p>

<pre class="lang-r prettyprint-override"><code>~F-&gt;y;cat(`if`(T&gt;0,&quot;Hello world!&quot;,scan(,T)))
</code></pre>
<p><a href="https://tio.run/##K/qfmVeWWZyZlJOqEVxZrFecWpKTn5wI5CUnlqSm5xdVKtgqKPk4xzv6@CjpKEDkQELOSpqa/@vcdO0qrYEqNRIy0xI0QuwMdJQ8UnNy8hXK84tyUhSVdIqTE/M0dEI0gYq5/gMA" rel="nofollow noreferrer" title="R – Try It Online">Try it online!</a></p>
<p>Cat:</p>

<pre class="lang-r prettyprint-override"><code>'-&gt;T;cat(sQuote(T),T)' -&gt;T;cat(sQuote(T),T)~F-&gt;y;cat(`if`(T&gt;0,&quot;Hello world!&quot;,scan(,T)))
</code></pre>
<p><a href="https://tio.run/##K/qfmVeWWZyZlJOqEVxZrFecWpKTn5wI5CUnlqSm5xdVKtgqKPk4xzv6@CjpKEDkQELOSpqa/9V17UKsgQo1igNL80tSNUI0dUI01RWwida56dpVgkUTMtMSNELsDHSUPFJzcvIVyvOLclIUlXSKkxPzNIAqgeZm5hWUlnD9BwA" rel="nofollow noreferrer" title="R – Try It Online">Try it online!</a></p>
<p>A 'trivial quine' version could be Quine = <code>~1</code>, and Hello, world = <code>+F-&gt;y;cat(`if`(y&lt;0,scan(,''),'Hello world!'))</code>, for <strong>2+45=47 bytes</strong>.</p>
<p><strong>How? (nontrivial &amp; trivial versions)</strong></p>
<p>The default behaviour of <a href="https://www.r-project.org/" rel="nofollow noreferrer">R</a> is to output any unassigned values (such as variables or expressions).  So, to print a quine, we simply need to generate an expression containing the program code, and it is output by default (this applies both to the nontrivial quine, which is contructed using <code>cat</code> to join the various text elements together, as well as the trivial quine <code>~1</code> consisting simply of a formula which is outputted)</p>
<p>If a value is assigned to a variable, it is not output.  So to stop the quines from printing, we incorporate them into an expression and assign this to the variable <code>y</code>.</p>
<p>To do this, we need to use a binary operator, but since this operator will also appear at the start of the 'Hello, world' program, it must also function as a unary operator.  Both the <code>~</code> (formula) and <code>+</code> (positive/sum) operators have this property.</p>
<p>Conveniently, <a href="https://www.r-project.org/" rel="nofollow noreferrer">R</a> also includes a (little used outside coding challenges) left-to-right assignment operator, <code>-&gt;</code>, which - together with a unary/binary operator - lets us package the quine into the variable <code>y</code> &amp; forget about it.  Then all we need to do is to determine whether this has happened or not, and use this to switch between 'Hello, world' and 'cat' behaviour.</p>
</div>
<div id="pu16" class="pu"><h1>Python 3, Cat + Quine = Hello World, 121 bytes</h1>
<ul>
<li>-2 bytes thanks to @Jo King</li>
</ul>
<p><strong>Cat</strong>:</p>
<p>Actual <code>cat</code> part is taken from the top comment of <a href="https://stackoverflow.com/a/40462515/4608364">this SO answer</a>.</p>
<p>If the file is long enough, switch to a Hello World program.</p>
<pre><code>len(open(__file__).read())&lt;99or~print('Hello World!')
import sys
print(sys.stdin.read())
</code></pre>
<p>The <code>~print</code> exits the program after printing: <code>print</code> returns <code>None</code> and <code>~None</code> throws. (Crashing to exit was allowed by OP in a comment.)</p>
<p><strong>Quine</strong>:</p>
<p>Pretty standard. Originally wanted to use Python 3.8 <code>:=</code> to do <code>print((s:='print((s:=%r)%%s)')%s)</code>, but that was longer. Stole the use of <code>;</code> instead of <code>\n</code> from <a href="https://codegolf.stackexchange.com/a/209043/43266">one of the other Python answers</a>.</p>
<pre><code>s='s=%r;print(s%%s)';print(s%s)

</code></pre>
<p><strong><a href="https://tio.run/##PU27CsMwDNz9Fe5gbC2BtlNos@cPMpqCXSpwJSN5yZJfT01fyz24O66u7cF03veSKXDtEOMdS44RBsm3FACu48iyVUFqwc@5FLYLS0kHDwaflaVZXdV8Cl0N2hLSb2108jo5uXxz5xT83yiYfo2U7dG86fQC" rel="nofollow noreferrer">Combined</a></strong>:</p>
<pre><code>len(open(__file__).read())&lt;99or~print('Hello World!')
import sys
print(sys.stdin.read())
s='s=%r;print(s%%s)';print(s%s)

</code></pre>
</div>
<div id="pu17" class="pu"><h1><a href="https://www.r-project.org/" rel="nofollow noreferrer">R</a>, Quine (<s>74</s> 51 bytes) + Cat (<s>77</s> 74 bytes) = <a href="https://tio.run/##dY2xCsIwFEV3vyJmaR68ip1LC1IoDlnE7LbGVAIhkSQqXfz1GK2r4z3nwPVJ24cO@mwUO85hE1Q0To55yTGqq/MzaQjl3WnHOUWyuA/qKEAqyravRbOtc8zC4e6iYj1gDwX5Z15V2c5fOuhpYKKtMNy8tnFiAn@hAMDFYpCjZUgpIN0rYxx5Om8u63wOaZXe" rel="nofollow noreferrer">Hello world</a> <s>151</s> 125 bytes</h1>
<h1><a href="https://www.r-project.org/" rel="nofollow noreferrer">R</a>, Hello world (<s>173</s> 174 bytes) + Cat (<s>77</s> 74 bytes) = <a href="https://tio.run/##K/qfmVeWWZyZlJOqEVxZrFecWpKTn5wI5CUnlqSm5xdVKtgqKPk4xzv6@CjpKEDkQELOSpqa/@sMde0qrUNs1WEM1WJroD6NhMy0BA03GwOd4uTEPA0dJSVNHSWP1JycfIXy/KKcFEWgXogOuOIQO0Od4oKizLySNI0QneLA0vySVI0QTU0diCwegzTV6W/lf67/AA" rel="nofollow noreferrer">Quine</a> <s>250</s> 248 bytes</h1>
<h1><a href="https://www.r-project.org/" rel="nofollow noreferrer">R</a>, Quine (<s>74</s> 51 bytes) + Hello world (<s>173</s> 174 bytes) = <a href="https://tio.run/##jZCxCsIwEIZ3nyIGJDlIpZ21BSkEhy5idltrKoHQlCRVuvjqNVp1U9zu7vvufjg7qvainDpqSfeDWzrptamr0NWVl2djB5QiXOSHTVFghib2GOUYYCRRxlcijVdBpm7XGy8pB8aBoG/klkTZEAh5Fwv3dErVlJSvY@bqqqUMY2B4K7U26GqsPs1D3LTxkUWWMNdZ1fqGCvbKEABsoj8OAfk3Mnyn6/1svAM" rel="nofollow noreferrer">Cat</a> <s>247</s> 225 bytes</h1>
<p><strong>A set of Quine, Cat &amp; Hello world from which any 2 can be combined to form the third.</strong></p>
<p>Not the shortest answer, but pleasingly symmetric.</p>
<p><strong>Quine (<s>74</s> 51 bytes)</strong></p>

<pre class="lang-r prettyprint-override"><code>'-&gt;F;T=0;cat(sQuote(F),F)' -&gt;F;T=0;cat(sQuote(F),F)
</code></pre>
<p><a href="https://tio.run/##K/qfmVeWWZyZlJOqEVxZrFecWpKTn5wI5CUnlqSm5xdVKtgqKPk4xzv6@CjpKEDkQELOSpqa/9V17dysQ2wNrIGKNYoDS/NLUjXcNHXcNNUVcMn8/w8A" rel="nofollow noreferrer" title="R – Try It Online">Try it online!</a></p>
<p><strong>Cat (<s>77</s> 74 bytes)</strong></p>

<pre class="lang-r prettyprint-override"><code>~1-&gt;y;cat(`if`(T&gt;1,sprintf(T,sQuote(T)),`if`(T,scan(,&quot;&quot;),&quot;Hello world!&quot;)))
</code></pre>
<p><a href="https://tio.run/##JY7BCsIwEER/Jea0C6vQs1iQXjzkIuZuY0wlEJqSTZVc/PUY6XHmPYZJ1c9vz/4RHNwKH9jlEK1pyZrsXjEVcRJSDfezUpLExv7VIBHrt9v35dhMGP00gu474iX5OU@gia9rzA40Im2U2JoZSEokeXEhRPGJKTx3bQnbjWXN9Qc" rel="nofollow noreferrer" title="R – Try It Online">Try it online!</a></p>
<p><strong>Hello world (<s>173</s> 174 bytes)</strong></p>

<pre class="lang-r prettyprint-override"><code>~1-&gt;y;T='~1-&gt;y;T=%s;cat(`if`(F&lt;0,scan(,&quot;&quot;),&quot;Hello world!&quot;))~1-&gt;y;cat(`if`(T&gt;1,sprintf(T,sQuote(T)),`if`(T,scan(,&quot;&quot;),&quot;Hello world!&quot;)))';cat(`if`(F&lt;0,scan(,&quot;&quot;),&quot;Hello world!&quot;))
</code></pre>
<p><a href="https://tio.run/##K/qfmVeWWZyZlJOqEVxZrFecWpKTn5wI5CUnlqSm5xdVKtgqKPk4xzv6@CjpKEDkQELOSpqa/@sMde0qrUNs1WEM1WJroD6NhMy0BA03GwOd4uTEPA0dJSVNHSWP1JycfIXy/KKcFEWgXogOuOIQO0Od4oKizLySNI0QneLA0vySVI0QTU0diCwegzTVibXy/38A" rel="nofollow noreferrer" title="R – Try It Online">Try it online!</a></p>
</div>
<div id="pu18" class="pu"><h1>Quine + Cat = Hello World, <a href="https://github.com/DennisMitchell/jelly" rel="nofollow noreferrer">Jelly</a>, 25 bytes</h1>
<p><em>-2 bytes thanks to @Jonathan Allan</em></p>
<h3>Quine (12 bytes)</h3>
<pre><code>
“Ṿṭ⁷;⁾v`”v`
</code></pre>
<p>(starts with a newline)</p>
<p><a href="https://tio.run/##y0rNyan8/5/rUcOchzv3Pdy59lHjdutHjfvKEh41zC1L@P//v5KSkqGRsYlOYlIykAkA" rel="nofollow noreferrer">Try it online!</a></p>
<h3>Cat (13 bytes)</h3>
<pre><code>Ṇ
“,ḷṅḳȦ»³ÑƑ?
</code></pre>
<p><a href="https://tio.run/##ATIAzf9qZWxsef//4bmGCuKAnCzhuLfhuYXhuLPIpsK7wrPDkcaRP////yIxMjM0LCdhYmMnIg" rel="nofollow noreferrer">Try it online!</a> (argument quoted to avoid casting to a Python object from string as per @Jonathan Allan's suggestion)</p>
<h3>Hello World (25 bytes)</h3>
<pre><code>
“Ṿṭ⁷;⁾v`”v`Ṇ
“,ḷṅḳȦ»³ÑƑ?
</code></pre>
<p>(starts with a newline)</p>
<p><a href="https://tio.run/##AUoAtf9qZWxsef//CuKAnOG5vuG5reKBtzvigb52YOKAnXZg4bmGCuKAnCzhuLfhuYXhuLPIpsK7wrPDkcaRP////yIxMjM0LCdhYmMnIg" rel="nofollow noreferrer">Try it online!</a></p>
<h2>How it Works</h2>
<p>In Jelly, the last link (last line) is always executed as the main link. The Cat and Hello World have the same last link, so they are differentiated by the value of the first link (blank (identity) or <code>Ṇ</code> (logical not)).</p>
<pre><code>“,ḷṅḳȦ»³ÑƑ?
          ?  # If
        ÑƑ   # The first link is the identity
“,ḷṅḳȦ»        # Return &quot;Hello World!&quot; (String Compressor: https://codegolf.stackexchange.com/a/151721/68261)
             # Else
       ³       # Return the input
</code></pre>
<p>The quine is slightly difficult because it needs to prepend a blank line.</p>
<pre><code>“Ṿṭ⁷;⁾v`”v` 
“Ṿṭ⁷;⁾v`”     # Set the string &quot;Ṿṭ⁷;⁾v`&quot;
         v`   # Eval it on itself:
 Ṿṭ⁷;⁾v`
 Ṿ              # Uneval: &quot;“Ṿṭ⁷;⁾v`”&quot;
  ṭ⁷            # Prepend a newline &quot;¶“Ṿṭ⁷;⁾v`”&quot;
    ;⁾v`        # Concatenate &quot;v`&quot; to get &quot;¶“Ṿṭ⁷;⁾v`”v`&quot;
</code></pre>
</div>
<div id="pu19" class="pu"><h1><a href="https://github.com/DennisMitchell/jelly" rel="nofollow noreferrer">Jelly</a>, Quine + Cat = Hello World! 17 <a href="https://github.com/DennisMitchell/jelly/wiki/Code-page" rel="nofollow noreferrer">bytes</a></h1>
<p><sup>Note that using a formatted input has been deemed valid and this entry takes input as a command-line argument formatted as a Python string. To have a pure-Cat program we'd need to use STDIN in Jelly, since it first attempts to evaluate any command-line argument as Python. This is achievable in 21 bytes with <code>”ṘṘ</code> + <code>”1$0¡ƈȮ¤L¿“,ḷṅḳȦ»Ṇ?</code> <a href="https://tio.run/##AT4Awf9qZWxsef//4oCd4bmY4bmYMSQwwqHGiMiuwqRMwr/igJws4bi34bmF4bizyKbCu@G5hj///1NvbWUKdGV4dA" rel="nofollow noreferrer">TIO</a>.</sup></p>
<pre><code>”ṘṘ
</code></pre>
<p><strong><a href="https://tio.run/##y0rNyan8//9Rw9yHO2cA0f///5WC83NTFUpSK0qUAA" rel="nofollow noreferrer" title="Jelly – Try It Online">Quine</a></strong></p>
<pre><code>1$0¡³“,ḷṅḳȦ»⁼?
</code></pre>
<p><strong><a href="https://tio.run/##ATEAzv9qZWxsef//MSQwwqHCs@KAnCzhuLfhuYXhuLPIpsK74oG8P////yJTb21lIHRleHQi" rel="nofollow noreferrer" title="Jelly – Try It Online">Cat</a></strong></p>
<pre><code>”ṘṘ1$0¡³“,ḷṅḳȦ»⁼?0
</code></pre>
<p><strong><a href="https://tio.run/##AToAxf9qZWxsef//4oCd4bmY4bmYMSQwwqHCs@KAnCzhuLfhuYXhuLPIpsK74oG8P////yJTb21lIHRleHQi" rel="nofollow noreferrer" title="Jelly – Try It Online">Hello World!</a></strong></p>
<h3>How?</h3>
<p>The shortest proper quine in Jelly is:</p>
<pre><code>”ṘṘ - Main Link: any arguments
”Ṙ  - an 'Ṙ' character
  Ṙ - print Jelly representation of x (i.e. ”Ṙ) and yield x ('Ṙ')
    - implicit print (i.e. Ṙ)
</code></pre>
<p>To use it we need to not let the <code>Ṙ</code> execute in the largest program.</p>
<p>One way to not execute a link is to follow it with <code>0¡</code> - repeat zero times, but <code>¡</code> needs a link to repeat, like <code>X0¡</code>, so we make <code>X</code> equal <code>1$</code>.</p>
<p><code>$</code> composes the preceding two links into a single monadic link and (slightly surprisingly) <code>1$</code> can start a full program, as a monad which yields <span class="math-container">\$1\$</span> but when repeated zero times it just yields whatever its left argument is.</p>
<p>As such starting a program which has one command-line argument with <code>1$0¡</code> applies <code>1$</code> zero times to that argument, i.e. is a no-op, giving the rest of the program that same left argument.</p>
<p>But when <code>1$0¡</code> is prefixed with <code>”ṘṘ</code> we have the <code>X</code> (described earlier) equal to <code>Ṙ1</code> which when applied zero times to <code>”Ṙ</code> yields the character <code>'Ṙ'</code>.</p>
<p>Since the character, <code>'Ṙ'</code>, is not equal to the right argument of the Main Link (which, when given a single command-line argument is that argument) since that is a <em>list</em> of characters, we can use equality, <code>⁼</code>, to test, <code>?</code>, (effectively) whether the prefix <code>”ṘṘ</code> is present and either...</p>
<p>...Cat* (if not):</p>
<pre><code>³ - yield the programs 1st command-line argument
</code></pre>
<p>...or Hello World!:</p>
<pre><code>“,ḷṅḳȦ» - compressed string = &quot;Hello World!&quot;
</code></pre>
<hr />
<p>* The Cat code for the 21 byte STDIN version is:</p>
<pre><code>ƈȮ¤L¿ - niladic link (no arguments)
    ¿ - do...
  ¤   - ...instruction: nilad followed by link(s) as a nilad
ƈ     -   read a character from STDIN
 Ȯ    -   print &amp; yield
   L  - ...while?: length (0 at EOF)
</code></pre>
<p>and we use the monad logical-NOT, <code>Ṇ</code>, as our test since we get an implicit left argument of <code>0</code> with no command-line arguments and by this point <code>Ṇ</code> gets an argument of <code>0</code> (<code>0Ṇ</code> = <span class="math-container">\$1\$</span> -&gt; Cat) or <code>'Ṙ'</code> (<code>”ṘṆ</code> = <span class="math-container">\$0\$</span> -&gt; Hello World!).</p>
</div>
<div id="pu20" class="pu"><h1>PHP, Hello World + Quine = Cat, 117 bytes</h1>
<p>Because of the input method this only works using the command line.</p>
<h2>Hello world</h2>
<p>the double die is because the php code has to get interupted earlier in order to prevent errors being printed (missing function a)</p>
<pre><code>&lt;?php if(!function_exists('a')){die('Hello world!');}die(a($argv));
</code></pre>
<h2>Quine</h2>
<p>without opening tag, php just outputs whatever it contains</p>
<pre><code>function a($b){unset($b[0]);echo implode(' ',$b);}
</code></pre>
<h2>Cat</h2>
<p>Because function declations are passed first, the die() isn't called yet and therefor a() exists, and is called in order to print its arguments. The unset avoids the scriptname from being printed (which is not an input)</p>
<pre><code>&lt;?php if(!function_exists('a')){die('Hello world!');}die(a($argv));function a($b){unset($b[0]);echo implode(' ',$b);}
</code></pre>
<p>If only the first argument has to be printed, a shortcut can be used (101 bytes):</p>
<pre><code>&lt;?php if(!function_exists('a')){die('Hello world!');}die(a($argv));function a($b){unset($b[0]);echo implode(' ',$b);}
</code></pre>
<p>This however is not the full input and i consider this invalid</p>
</div>
<div id="pu21" class="pu"><h1><a href="https://github.com/DJMcMayhem/V" rel="nofollow noreferrer">V (vim)</a>, Quine + Hello World = Cat, 32 bytes</h1>
<h2>Quine</h2>
<pre><code>dG2idG2i
</code></pre>
<p>Explanation:</p>
<ul>
<li><code>dG</code>: Delete the buffer (saving it to the unnamed register)</li>
<li><code>2idG2i</code>: Insert <code>dG2i</code> twice.</li>
</ul>
<h2>Hello World</h2>
<pre><code>&quot;_dG4iHello World!
␛pH3D
</code></pre>
<p>With trailing newline. TryItOnline also shows a trailing space after that, but this appears to be an artifact of it's V runner.</p>
<p>Explanation:</p>
<ul>
<li><code>&quot;_dG</code>: Delete the buffer (without saving it to a register)</li>
<li><code>4iHello World!␊␛</code>: Write &quot;Hello World!&quot; 4 times</li>
<li><code>p</code>: Paste from the (empty) unnamed register</li>
<li><code>H3D</code>: Delete the first 3 lines of the buffer</li>
</ul>
<h2>Cat</h2>
<pre><code>dG2idG2i&quot;_dG4iHello World!
␛pH3D
</code></pre>
<p>Since all no-ops in V are automatically cat programs, the trick here is to make the combined program cancel out itself.</p>
<p>Explanation:</p>
<ul>
<li><code>dG</code>: Delete the buffer (saving it to the unnamed register)</li>
<li><code>2idG2i&quot;_dG4iHello World!␊␛</code>: Write <code>dG2i&quot;_dG4iHello World!</code> twice (trailing newline)</li>
<li><code>p</code>: Paste from the unnamed register.
<ul>
<li>Since the motion used to delete was <code>G</code>, this pastes it onto the following line.</li>
<li>Therefore, the first two lines of the buffer are that crazy string, the third is an empty line, and the rest is the original buffer</li>
</ul>
</li>
<li><code>H3D</code>: Delete the first 3 lines of the buffer</li>
</ul>
<p><a href="https://tio.run/##K/v/P8XdKBOEleJT3E0yPVJzcvIVwvOLclIUuWxSi5PtCjxSjFP@/w/JSFUoLM1MzlZIKsovz1NIy6/gyirNLShWyC9LLVIoAUrnJFZVKqTkp//XLQMA" rel="nofollow noreferrer" title="V (vim) – Try It Online">Try it online!</a></p>
</div>
<div id="pu22" class="pu"><h1><a href="https://docs.python.org/2/" rel="nofollow noreferrer">Python 2</a>, Hello World + Cat = Quine, <strike>200</strike> <strike>198</strike> 189 bytes</h1>

<h2>Hello World</h2>
<pre class="lang-python prettyprint-override"><code>id=0;a=&quot;Hello World!&quot;;a0='id=0;a=&quot;%s&quot;;a0=%r;print a0%%((a,a0)if id&lt;1else 1)\nimport sys\nif id:print sys.stdin.read()';print a
</code></pre>
<h2>Cat</h2>
<pre class="lang-python prettyprint-override"><code>0%((a,a0)if id&lt;1else 1)
import sys
if id:print sys.stdin.read()
</code></pre>
<p>My previous answer was actually wrong. <code>raw_input</code> only reads one line. This reads the entire input.</p>
<h2>Quine</h2>
<pre class="lang-python prettyprint-override"><code>id=0;a=&quot;Hello World!&quot;;a0='id=0;a=&quot;%s&quot;;a0=%r;print a0%%((a,a0)if id&lt;1else 1)\nimport sys\nif id:print sys.stdin.read()';print a0%((a,a0)if id&lt;1else 1)
import sys
if id:print sys.stdin.read()
</code></pre>
<p><a href="https://tio.run/##fc7BCsIwDAbge58iDspakNF5dPbuG3jxEmjFQE1LW5E9/ayK7CLekvz8H0lzvUbeLQs5aya03dGHEOEUc3CbbkJj@28iy3uXeUqZuAIaKZXCLRpNFyB3GH0oHkZ9ZrqlmCuUubT5le0/lXYYSnXEQ/bolO5X6qckVkj8c9r7nO7NKfDIVKtnwSkyiyc" rel="nofollow noreferrer" title="Python 2 – Try It Online">Try it online!</a></p>
<hr />
<p><em>2020-08-05: -42 bytes thanks to Jonathan Allen, +33 to fix a bug</em></p>
</div>
<div id="pu23" class="pu"><h1><a href="http://esolangs.org/wiki/Fish" rel="nofollow noreferrer">&gt;&lt;&gt;</a>, Quine + Cat = Hello World!, 48 bytes</h1>
<p><strong><a href="https://tio.run/##S8sszvj/X6nIwCA9P8de0drEQO//fwA" rel="nofollow noreferrer">Quine</a></strong></p>
<p><code>&quot;r00gol?!;40.</code></p>
<p>The classic &gt;&lt;&gt; quine</p>
<p><strong><a href="https://tio.run/##S8sszvj/Xym2TCnTykDD3jqfyy7HXhFIxSl5pObk5CuE5xflpCgq2fz/X5JaXAIA" rel="nofollow noreferrer">Cat</a></strong></p>
<pre><code>&quot;]v&quot;i:0(?;o
&gt;l?!;o
^&quot;Hello World!&quot;&lt;
</code></pre>
<p>A simple cat program, loaded with some other code that isn't being run.</p>
<p><strong><a href="https://tio.run/##S8sszvj/X6nIwCA9P8de0drEQE8ptkwp08pAw946n8sOJJbPFafkkZqTk68Qnl@Uk6KoZPP/PwA" rel="nofollow noreferrer">Hello World!</a></strong></p>
<pre><code>&quot;r00gol?!;40.&quot;]v&quot;i:0(?;o
&gt;l?!;o
^&quot;Hello World!&quot;&lt;
</code></pre>
<p>The quine part makes the instruction pointer stop interpreting &quot;]v&quot; as text, instead clearing the stack and moving down to the &quot;Hello World!&quot; printer.</p>
<hr>
<p>Equivalently, the program can be written as</p>
<pre><code>'rd3*ol?!;40.']v'i:0(?;o
&gt;l?!;o
^&quot;Hello World!&quot;&lt;
</code></pre>
<p>Which, as Jo King points out, avoids using the <code>g</code> code reflection instruction, arguably making the quine more genuine.</p>
</div>
<div id="pu24" class="pu"><h1><a href="https://github.com/Adriandmen/05AB1E/wiki/Commands" rel="nofollow noreferrer">05AB1E</a>, Quine + Hello World = Cat, 23 <a href="https://github.com/Adriandmen/05AB1E/wiki/Codepage" rel="nofollow noreferrer">bytes</a></h1>
<p><strong>Quine:</strong></p>
<pre><code>2096239D20BJ
</code></pre>
<p><a href="https://tio.run/##yy9OTMpM/f/fyMDSzMjY0sXIwMnr//@S1OISAA" rel="nofollow noreferrer">Try it online (with input)</a> or <a href="https://tio.run/##yy9OTMpM/f/fyMDSzMjY0sXIwMnr/38A" rel="nofollow noreferrer">try it online (without input)</a>.</p>
<p><strong>Hello World:</strong></p>
<pre><code>I.gi”Ÿ™‚ï!
</code></pre>
<p><a href="https://tio.run/##yy9OTMpM/f/fUy8981HD3KM7HrUsetQw6/B6xf//S1KLSwA" rel="nofollow noreferrer">Try it online (with input)</a> or <a href="https://tio.run/##yy9OTMpM/f/fUy8981HD3KM7HrUsetQw6/B6xf//AQ" rel="nofollow noreferrer">try it online (without input)</a>.</p>
<p><strong>Cat:</strong></p>
<pre><code>2096239D20BJI.gi”Ÿ™‚ï!
</code></pre>
<p><a href="https://tio.run/##yy9OTMpM/f/fyMDSzMjY0sXIwMnLUy8981HD3KM7HrUsetQw6/B6xf//S1KLSwA" rel="nofollow noreferrer">Try it online (with input)</a> or <a href="https://tio.run/##yy9OTMpM/f/fyMDSzMjY0sXIwMnLUy8981HD3KM7HrUsetQw6/B6xf//AQ" rel="nofollow noreferrer">try it online (without input)</a>.</p>
<p>(All three output with trailing newline.)</p>
<p><strong>Explanation:</strong></p>

<pre class="lang-python prettyprint-override"><code>2096239       # Push integer 2096239
       D      # Duplicate it
        20B   # Convert it to base-20 as list: &quot;D20BJ&quot;
           J  # Join stack together: &quot;2096239D20BJ&quot;
              # (after which it is output implicitly as result)

I             # Push the input (or an empty string if none is given)
 .g           # Get the amount of items on the stack (which will be 1)
   i          # If this amount is 1 (which it always is):
    ”Ÿ™‚ï!    #  Push dictionary string &quot;Hello World!&quot;
              #  (after which it is output implicitly as result)

2096239D20BJ  # Same as above
I             # Push the input (or an empty string if none is given)
 .g           # Get the amount of items on the stack: 2
   i          # If this amount is 1 (which it isn't):
    ”Ÿ™‚ï!    #  Push dictionary string &quot;Hello World!&quot;
              # (implicit else:)
              #  (implicitly output the input we pushed earlier as result)
</code></pre>
<p><a href="https://codegolf.stackexchange.com/a/166851/52210">See this 05AB1E tip of mine (section <em>How to use the dictionary?</em>)</a> to understand why <code>”Ÿ™‚ï!</code> is <code>&quot;Hello World!&quot;</code>.<br />
Credit of the quine goes to <a href="https://codegolf.stackexchange.com/a/186809/52210"><em>@Grimmy</em>'s answer here</a>.</p>
</div>
<div id="pu25" class="pu"><h1>Hello World + Quine = Cat, C (GCC), 149 (81 + 68)</h1>
<h3>Hello World</h3>
<pre><code>a;main(s){a?read(0,&amp;s,1)&amp;&amp;main(putchar(s)):puts(&quot;Hello World!&quot;);}
#define main m
</code></pre>
<p><a href="https://tio.run/##S9ZNT07@/z/ROjcxM0@jWLM60b4oNTFFw0BHrVjHUFNNDSxeUFqSnJFYBJTXtAKyizWUPFJzcvIVwvOLclIUlTSta7mUU1LTMvNSFUDqFXL//w/JyCxWAKKSjFSFzDygJgA" rel="nofollow noreferrer" title="C (gcc) – Try It Online">Try it online!</a></p>
<h3>Quine</h3>
<pre><code>a=1;main(s){printf(s=&quot;a=1;main(s){printf(s=%c%s%1$c,34,s);}&quot;,34,s);}
</code></pre>
<p><a href="https://tio.run/##S9ZNT07@/z/R1tA6NzEzT6NYs7qgKDOvJE2j2FYJq6hqsmqxqqFKso6xiU6xpnWtEozx/z8A" rel="nofollow noreferrer" title="C (gcc) – Try It Online">Try it online!</a></p>
<h3>Cat (Hello World + Quine)</h3>
<pre><code>a;main(s){a?read(0,&amp;s,1)&amp;&amp;main(putchar(s)):puts(&quot;Hello World!&quot;);}
#define main m
a=1;main(s){printf(s=&quot;a=1;main(s){printf(s=%c%s%1$c,34,s);}&quot;,34,s);}
</code></pre>
<p><a href="https://tio.run/##S9ZNT07@/z/ROjcxM0@jWLM60b4oNTFFw0BHrVjHUFNNDSxeUFqSnJFYBJTXtAKyizWUPFJzcvIVwvOLclIUlTSta7mUU1LTMvNSFUDqFXK5Em0N4UYWFGXmlaRpFNsqYRVVTVYtVjVUSdYxNtEpBhqlBGP8/x@SkVmsAEQlGakKmXlAmwE" rel="nofollow noreferrer" title="C (gcc) – Try It Online">Try it online!</a></p>
</div>
<div id="pu26" class="pu"><h1><a href="https://github.com/m-ender/alice" rel="nofollow noreferrer">Alice</a>, Cat + Quine = Hello World, 51 bytes</h1>
<p><strong>Cat:</strong> (With trailing newline)</p>
<pre><code>\ &gt;  &quot;!dlroW olleH&quot;d&amp;O@
  ^/ v
  # &lt; i
</code></pre>
<p><a href="https://tio.run/##S8zJTE79/z9GwU5BQUkxJacoP1whPycn1UMpRc3fgUtBIU5foQxIKSvYKGRy/f@flp@flFgEAA" rel="nofollow noreferrer">Try it online.</a></p>
<p>Uses # to skip the redirect west and instead hit the redirect south into the i, which pushes the input as a string to the top of the stack. The instruction pointer then reflects off the top and bottom boundaries of the grid, hitting the o and @ from the Hello World program, causing it to output the top of the stack as a string and then terminate. The code requires a trailing newline, which I couldn't get to display here in the code block.</p>
<p><strong>Quine:</strong></p>
<pre><code>&quot;!&lt;@O&amp;9h.
</code></pre>
<p><a href="https://tio.run/##S8zJTE79/19J0cbBX80yQ@///7T8/KTEIgA" rel="nofollow noreferrer">Try it online.</a></p>
<p>Just a standard Alice quine.</p>
<p><strong>Hello World:</strong></p>
<pre><code>\ &gt;  &quot;!dlroW olleH&quot;d&amp;O@
  ^/ v
  # &lt; i
&quot;!&lt;@O&amp;9h.
</code></pre>
<p><a href="https://tio.run/##S8zJTE79/z9GwU4hQUkxJacoP1whPycn1UMpJUHN34FLQSFOX6EMSCkr2Chkcikp2jj4q1lm6P3/n5afn5RYBAA" rel="nofollow noreferrer">Try it online.</a></p>
<p>The # is now used to skip the @ from the quine program, causing the instruction pointer to instead hit the redirect west, which passes through a mirror and hits two more redirects to hit a standard Alice Hello World program.</p>
</div>
<div id="pu27" class="pu"><h1><a href="https://www.rust-lang.org/" rel="nofollow noreferrer">Rust</a>, Quine + Cat = Hello, world! (106 + 2 = 108 bytes)</h1>
<h3>Quine (<s>108</s> 106 bytes):</h3>
<p>-2 bytes: removed ',' from &quot;Hello world!&quot;</p>
<pre><code>let s=format!(&quot;Hello world!&quot;);format!(&quot;{},{0:?})&quot;,&quot;let s=format!(\&quot;Hello world!\&quot;);format!(\&quot;{},{0:?})\&quot;&quot;)
</code></pre>
<p><code>.into()</code> instead of <code>format!</code> saves a few bytes but is context-dependent.</p>
<h3>Cat (2 bytes):</h3>
<pre><code>;s
</code></pre>
<h3>Quine + Cat = Hello, world! (<s>110</s> 108 bytes):</h3>
<pre><code>let s=format!(&quot;Hello world!&quot;);format!(&quot;{},{0:?})&quot;,&quot;let s=format!(\&quot;Hello world!\&quot;);format!(\&quot;{},{0:?})\&quot;&quot;);s
</code></pre>
<p><a href="https://tio.run/##xZHBTsMwDIbveQrPB0ikwDi3MG4VRySuvYQt3SKlyUhcTajrs5e0Qy1jHLjNp9@OP@uPHZpIfV85qJVxXEDLIAXpSHxUQ@BaEcopPcZjasvjVOhGJfK/0I/GOH0BW00QnyofakULji/aWg8HH@xmgSKf6m0n24fsuRMo8Rwpz5jyB1TOVIko/mVyN8@6otXLjbKOsXSawe1jseJO1TqDm9tIiswaIgUJVQaFYIedDnpkipQ7/kbBuK2AuxWcJDvddZ80WZf8vga/DarOoO1QwjD5ezVzy/hScTRu3xDep7LnQvxuEzksl5C@BEGrjXo31tBnMt73Xw" rel="nofollow noreferrer">Try it!</a></p>
<p>Updated to not use <code>include_str!</code>. Hopefully this doesn't break any rules anymore.</p>
<p>This relies on it being in a closure/function that implements <code>Fn(String) -&gt; String</code> with argument <code>s</code>.</p>
<hr />
<p>Old answer, uses <code>include_str!</code>:</p>
<h3>Quine (67 bytes):</h3>
<pre><code>match include_str!(&quot;f&quot;){p@_ if p.len()==67=&gt;p,_=&gt;&quot;Hello, world!&quot;}//
</code></pre>
<p>(Not very creative, unfortunately)</p>
<h3>Cat (1 byte):</h3>
<pre><code>s
</code></pre>
<h3>Quine + Cat = Hello, world! (68 bytes):</h3>
<pre><code>match include_str!(&quot;f&quot;){p@_ if p.len()==67=&gt;p,_=&gt;&quot;Hello, world!&quot;}//s
</code></pre>
<p><s>Try it! (Repl.it link due to multiple files)</s></p>
<p>This depends on the code being in its own file named &quot;f&quot; and being <code>include!</code>'d into main.rs before being executed. The Repl.it link has the programs in separate files with different names, which means that the quine and hello world programs are different by one character so that they include the correct string.</p>
<p><s>This challenge was especially difficult in Rust (without using a comment at the end of one of the programs) because of the syntax of the language. Functions and multi-statement closures have braces surrounding them, so you can't just concat two closures to get a third, unfortunately.</s></p>
</div>
<div id="pu28" class="pu"><h1><a href="https://github.com/aceto/aceto" rel="nofollow noreferrer">Aceto</a>, quine (67) + cat (33) = Hello World (100 bytes*)</h1>
<p>(*I counted one file including a final newline so that catting them together works as expected)</p>
<h3><a href="https://codegolf.stackexchange.com/a/209076/21173">quine</a> (made it for this challenge):</h3>
<pre><code>£&quot;24«cs%55«3+cp24«2+cdpsdpsppn&quot;24«cs%55«3+cp24«2+cdpsdpsppn
</code></pre>
<h3>cat:</h3>
<pre><code>X


n
p el
r&quot;HlX
^^ oldnp
 ^Wor!&quot;
</code></pre>
<hr />
<p>The quine itself was the hardest part, due to the nature of having code on a Hilbert curve (The &quot;Hello World&quot;, and cat programs are trivial compared to it). The solution of having the concatenated program do something else than the parts is simple in Aceto: Because the (longer-line) quine enforces a square size of an even power of two (64 = 2^6), and the cat program has, on its own, a square of size 8x8 (8 = 2^3, an odd power of two), the instruction pointer starts moving in a different direction.</p>
</div>
<div id="pu29" class="pu"><h1><a href="https://docs.python.org/3.8/" rel="noreferrer">Python 3</a>, Hello World + Quine = Cat, 129 bytes</h1>

<h3><a href="https://tio.run/##HczBCsIwDADQe74i7pTAGAMvInj3DzyOwqIGahvSDPTrq@7@ePaJZy3Hk3nv@rLqgbWNKeStgalhAruYawlIk8tDW4iTjcNVcq54q57Xw8Cwyh13RgufAY202BbEDL9uWv4bzdz7Fw" rel="noreferrer" title="Python 3.8 (pre-release) – Try It Online">Hello World</a>:</h3>
<pre class="lang-python prettyprint-override"><code>import os,atexit as a
p=print
a.register(p,&quot;Hello World!&quot;)
def print(_):
 p(input())
 os._exit(0)
</code></pre>
<h3><a href="https://tio.run/##K6gsycjPM7YoKPr/v9hWvdhWtci6oCgzr0SjWFW1WFMdzinW/P8fAA" rel="noreferrer" title="Python 3.8 (pre-release) – Try It Online">Quine:</a></h3>
<pre class="lang-python prettyprint-override"><code>s='s=%r;print(s%%s)';print(s%s)
</code></pre>
<h3><a href="https://tio.run/##PcxNCsIwEEDh/ZxiLIRmoBTBjSjZewOXJdCogdgMM1PQ08c/cPng4/HTbnXZ7Vlay3euYlh1iJYe2TAqRuDAkheDOEq6ZrUknofulEqpeK5S5k1HMKcLfpmf6ADIPi@8mieC926cPje/JdDQa3By/FF1Tqn/h1JrltRe" rel="noreferrer" title="Python 3.8 (pre-release) – Try It Online">Cat</a>:</h3>
<pre class="lang-python prettyprint-override"><code>import os,atexit as a
p=print
a.register(p,&quot;Hello World!&quot;)
def print(_):
 p(input())
 os._exit(0)
s='s=%r;print(s%%s)';print(s%s)
</code></pre>
<p><code>atexit</code> lets you define cleanup steps that will run when your program exits &quot;normally&quot;. In this case, I register the <code>print</code> function (renamed <code>p</code>) with the argument <code>&quot;Hello World!&quot;</code>, so it will print that string when the program ends.</p>
<p>I then redefine <code>print</code> to become a <code>cat</code> function. Normally, this would cause the program to print its input <em>and</em> &quot;Hello World!&quot;, but <code>os._exit()</code> is an &quot;abnormal&quot; exit that bypasses the cleanup steps.</p>
<p>Now that <code>print</code> has been redefined, the Quine simply calls this <code>cat</code> function and the program abruptly exits. If the Quine doesn't exist, then the program exits normally, printing &quot;Hello World!&quot; in the process.</p>
<p>The final program doesn't work on TIO, but it works for me running Python 3.7.3 on MacOS.</p>
</div>
<div id="pu30" class="pu"><h1>Bash, Quine + Cat = Hello World, 110 bytes</h1>
<h2><a href="https://tio.run/##S0oszvj/v9BWPbUsMUehoCgzryRNQUmlWAlMqFsX26oX2saYmGOVBooDFQBJ1WIQU6VQHYj//wcA" rel="noreferrer">Quine</a></h2>
<pre><code>q='eval printf &quot;$s&quot; &quot;$s&quot;';s='q=\47eval printf &quot;$s&quot; &quot;$s&quot;\47;s=\47%s\47;$q';$q
</code></pre>
<h2><a href="https://tio.run/##S0oszvj/v6SoNFUhLTGnOFVNLTmxpKYmNTkjX8EjNScnXyE8vygnRfH//4zE4pQ0CE6DMQE" rel="noreferrer">Cat</a></h2>
<pre><code>true false&amp;&amp;cat||echo Hello World!
</code></pre>
<h2><a href="https://tio.run/##S0oszvj/v9BWPbUsMUehoCgzryRNQUmlWAlMqFsX26oX2saYmGOVBooDFQBJ1WIQU6VQHYhLikpTFdISc4pT1dSSE0tqalKTM/IVPFJzcvIVwvOLclIU///PSCxOSYPgNBgTAA" rel="noreferrer">Hello World</a></h2>
<pre><code>q='eval printf &quot;$s&quot; &quot;$s&quot;';s='q=\47eval printf &quot;$s&quot; &quot;$s&quot;\47;s=\47%s\47;$q';$qtrue false&amp;&amp;cat||echo Hello World!
</code></pre>
<p>This takes advantage of the fact that undefined variables expand to the empty string and that <code>true</code> is a command that can take arguments.</p>
<p>You can trivially swap the cat and the hello world by swapping <code>true</code> and <code>false</code></p>
</div>

<table id="st">
<!-- Popups content will be added here -->
</table>

<table id="at">
<!-- Popups content will be added here -->
</table>

</div>





  <div class="footer">
      <b><a class="nonewtab" href="../">GOLFSCORE/</a><a href="https://codegolf.stackexchange.com/questions/209022/">209022</a></b>
  </div>
<div class="footer-space">&nbsp;</div>



<script src="../c.js"> </script>
</body>
</html>




